### ISSUE TITLE
Dodać język angielski

### ISSUE THREAD

**Issue by lukaszo** [hackerspace-silesia/hs-silesia.pl#10]
- [x] o nas
- [x] miejsce
- [x] dołącz do nas (pdf myślę, że może zostać po Polsku)
- [x] kontakt

**Comment by firemark** [comment]
@bartlomiejb robiłeś wczoraj tłumaczenia - jak wyszło? masz to gotowe?

**Comment by galuszkak** [comment]
Wygląda, że jest zrobione! Thanks @bartlomiejb :+1:
