### ISSUE TITLE
Deletion of branch on-site

### ISSUE THREAD

**Issue by Palid** [hackerspace-silesia/hs-silesia.pl#8]
On-site moved to master with removal of magic (moved to Magic branch).
Branch should be removed.

**Comment by Palid** [comment]
@firemark Usuń niepotrzebny branch - ja nie mam uprawnień.

**Comment by galuszkak** [comment]
@Palid ale jesteś colaborator powinnieneś mieć możliwość usunięcia brancha. Firemark też jest tylko collaboratorem...

**Comment by firemark** [comment]
Wszystkie issue ze stroną będę robić za tydzień - teraz nie mam czasu nawet na usunięcie

**Comment by firemark** [comment]
done.
